// Generated by https://quicktype.io

export interface IVillager {
    id:                   number;
    "file-name":          string;
    name:                 { [key: string]: string };
    personality:          string;
    "birthday-string":    string;
    birthday:             string;
    species:              string;
    gender:               string;
    subtype:              string;
    hobby:                string;
    "catch-phrase":       string;
    icon_uri:             string;
    image_uri:            string;
    "bubble-color":       string;
    "text-color":         string;
    saying:               string;
    "catch-translations": { [key: string]: string };
}
