// Generated by https://quicktype.io

export interface IVillagers {
    id:                   number;
    "file-name":          string;
    name:                 { [key: string]: string };
    personality:          Personality;
    "birthday-string":    string;
    birthday:             string;
    species:              string;
    gender:               Gender;
    subtype:              Subtype;
    hobby:                Hobby;
    "catch-phrase":       string;
    icon_uri:             string;
    image_uri:            string;
    "bubble-color":       string;
    "text-color":         string;
    saying:               string;
    "catch-translations": { [key: string]: string };
}

export enum Gender {
    Female = "Female",
    Male = "Male",
}

export enum Hobby {
    Education = "Education",
    Fashion = "Fashion",
    Fitness = "Fitness",
    Music = "Music",
    Nature = "Nature",
    Play = "Play",
}

export enum Personality {
    Cranky = "Cranky",
    Jock = "Jock",
    Lazy = "Lazy",
    Normal = "Normal",
    Peppy = "Peppy",
    Smug = "Smug",
    Snooty = "Snooty",
    Uchi = "Uchi",
}

export enum Subtype {
    A = "A",
    B = "B",
}
