import { Navbar } from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Provider } from '@/components/provider/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/Mario.png" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
